# Generated by Django 4.0.3 on 2022-03-21 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
                ('image', models.ImageField(upload_to='', verbose_name='GroupImage')),
                ('group_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='NameOfInterest')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name="User's e-mail")),
                ('date_of_birth', models.DateField(verbose_name="User's birth date")),
                ('description', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberOfGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupUp.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupUp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupUp.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroupUp.interest'),
        ),
        migrations.AddField(
            model_name='group',
            name='likedBy',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='GroupUp.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, through='GroupUp.MemberOfGroup', to='GroupUp.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='myLikes',
            field=models.ManyToManyField(blank=True, related_name='my_likes', to='GroupUp.group'),
        ),
    ]
