# Generated by Django 4.0.2 on 2022-02-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GroupUp.interest'),
        ),
    ]
