# Generated by Django 4.0.2 on 2022-02-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.AlterField(
            model_name='group',
            name='interests',
            field=models.ManyToManyField(blank=True, through='GroupUp.GroupHasInterest', to='GroupUp.Interest'),
        ),
    ]
