# Generated by Django 4.0.2 on 2022-03-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupUp', '0002_alter_group_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='likedBy',
            field=models.ManyToManyField(blank=True, through='GroupUp.LikedBy', to='GroupUp.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='myLikes',
            field=models.ManyToManyField(blank=True, through='GroupUp.Likes', to='GroupUp.Group'),
        ),
        migrations.AddField(
            model_name='likes',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupUp.group'),
        ),
        migrations.AddField(
            model_name='likedby',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupUp.group'),
        ),
    ]
